version: '3.4'

services:  

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: src/UserService/Dockerfile

  userservice-dapr:
    image: "daprio/daprd:latest"    
    network_mode: "service:userservice"
    depends_on:
      - userservice