version: '3.4'

services:  

  ##############################
  # user service + Dapr sidecar
  ##############################
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    depends_on:
      - redis
      - seq
      - placement
      - zipkin
    networks:
      - net-dapr    

  userservice-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - userservice
    network_mode: "service:userservice"
  
  ##############################
  # post service + Dapr sidecar
  ##############################
  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: src/PostService/Dockerfile
    depends_on:
      - redis
      - seq
      - placement
      - zipkin
    networks:
      - net-dapr    
  
  postservice-dapr:
    image: "daprio/daprd:edge"
    depends_on:
      - postservice
    network_mode: "service:postservice" 

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"    
    networks:
      - net-dapr  
  
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"    
    networks:
      - net-dapr
  seq:
    image: datalust/seq:latest
    networks:
      - net-dapr

  zipkin:
    image: openzipkin/zipkin-slim
    networks:
      - net-dapr

  

networks:
    net-dapr:  
