version: '3.4'

services:

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"            
      - "51000:50001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  userservice-dapr:
    command: ["./daprd",
      "-app-id", "user-service",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"