version: '3.4'

services:

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"            
      - "50001:50001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  userservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "user-service",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",      
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  postservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"            
      - "50002:50001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  postservice-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "post-service",
      "-app-port", "80",
      "-placement-host-address", "placement:50006",      
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  placement:    
    command: ["./placement", "-port", "50006"]    
    ports:
      - "50006:50006"   

  redis:    
    ports:
      - "6380:6379"

  seq:    
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
 
  zipkin:
    ports:
      - "5411:9411"